language: c++
compiler: gcc
sudo: required
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX, OF master
  - os: osx
    osx_image: xcode9
    compiler: clang
    env: TARGET="osx" OF_BRANCH="master"

# Linux ARM6, OF master: Uncomment following lines to enable
  - os: linux
    sudo: required
    dist: trusty
    env: TARGET="linuxarmv6l" OF_BRANCH="master"


# Linux ARM7, OF master: Uncomment following lines to enable
  - os: linux
    sudo: required
    env: TARGET="linuxarmv7l" OF_BRANCH="master"
    cache:
      directories:
        - ~/rpi2_toolchain
        - ~/firmware-master
        - ~/archlinux

  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

before_install:
  - echo "https://raw.githubusercontent.com/bakercp/ofxAddonScripts/${OF_BRANCH}/scripts/ci/tools/install.sh"
  - source <(curl -SLs https://raw.githubusercontent.com/bakercp/ofxAddonScripts/${OF_BRANCH}/scripts/ci/tools/install.sh)
install:
  - do_install
script:
  - do_script
git:
  depth: 10
